[package]
name = "pomodoro"
version = "0.1.0"
authors = ["osmak1234 <tadeashanus0631@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.20.1" }
